### ISSUE TITLE
Wednesday 12th April, GraphQL - Pre-Workshop instructions 

### ISSUE THREAD

**Issue by xoneco** [campus-experts/spring-2017#12]
Hello 👋 

I'll be doing a workshop next Wednesday about the GitHub GraphQL API 😄 

It's going to very hands on and you'll be able to do loads of stuff yourself! 
To do that quickly and not spend a lot of time setting up on the call itself, please follow the instructions in the below gist **before** the workshop:
https://gist.github.com/xoneco/96309b04f67d4ac029d1880ca26fc2aa

Once you're done, leave a 👍 on this issue, so I know you're good to go.

If you have any issues, post them here, or mention it in the [#tech-talks](slack://channel?team=T0NQLH3HB&id=C4U4PT189) channel on Slack.

See you on Wednesday ✌️

**Comment by joenash** [comment]
**Time:**
London, United Kingdom    Wed, 12 Apr 2017 at 17:00 BST     
San Francisco, USA        Wed, 12 Apr 2017 at 09:00 PDT     
New York, USA             Wed, 12 Apr 2017 at 12:00 EDT     
New Delhi, India          Wed, 12 Apr 2017 at 21:30 IST     
Taipei, Taiwan            Thu, 13 Apr 2017 at 00:00 CST     
Sydney, Australia         Thu, 13 Apr 2017 at 02:00 AEST  

**Link is:**
https://github.zoom.us/j/4245140792

**Comment by xoneco** [comment]
Thanks everyone for joining!

**Cool things to check out now:**
GraphQL Website: http://graphql.org
GitHub Universe talk by @kdaigle: https://www.youtube.com/watch?v=wPPFhcqGcvk
