### ISSUE TITLE
Awesome-Campus-Experts Repo

### ISSUE THREAD

**Issue by PandelisZ** [campus-experts/spring-2017#19]
Hey guys I was thinking it could be quite cool and useful to have a awesome list type repo for resources that would benefit campus experts. Similar to other [awesome lists](https://github.com/sindresorhus/awesome) across GitHub. 

We could include presentation or workshop resources that other CE's make available, maybe resources on running workshops, cool blog posts, community tools etc.

I'm looking for some feedback on if this would be useful to people, what sort of categories we should have and if you have any resources you'd like to share.

**Comment by BlueHatbRit** [comment]
Sweet idea, how about some sections like:

* Talks
* Workshops
* Game Jams / Hackathons / Events

Maybe if we group if that way then we could sub group tools and resources (articles etc)?

Linkwise:

* [Speaking.io](http://speaking.io/) - a cool website with some good tips on giving talks, focused on tech talks mostly.
* [FsReveal](https://github.com/fsprojects/FsReveal) there are loads of _x_Reveal projects out there, I quite like this FSharp one but I think there's a JS one as well.

**Comment by PandelisZ** [comment]
Oh cool didn't know it detects cross repo stuff, awesome!

But yeah thanks for the suggestions @BlueHatbRit the repo has been set up and I've made a PR with your suggestions
