### ISSUE TITLE
Campus Expert Office Hours, Git/GitHub intro

### ISSUE THREAD

**Issue by swinton** [campus-experts/spring-2017#22]
:wave: Greetings, Campus Experts!

I'm @swinton, and I'll be your guide for today's **Git/GitHub intro**. Here's our agenda...

- [x] What is a version control system?
- [x] What is Git? [Git](https://git-scm.com/)
- [x] What is GitHub? [The world’s leading software development platform · GitHub](https://github.com/)
- [x] What is a repository?
- [x] How to use Issues?
- [x] How to Markdown? [Mastering Markdown · GitHub Guides](https://guides.github.com/features/mastering-markdown/)
- [x] How to handle notifications? [Settings -> Notifications](https://github.com/settings/notifications)
- [x] What is the GitHub Flow? [Understanding the GitHub Flow · GitHub Guides](https://guides.github.com/introduction/flow/)
- [x] How to propose and collaborate on changes? [On Demand Training](https://services.github.com/on-demand/)
- [x] What are some other resources? [GitHub Services - Resources](https://services.github.com/resources/)
- [x] Q&A

Looking forward to it :smile:

**Comment by swinton** [comment]
Hello this is my comment, it might not be the best comment, but it is mine

**Comment by abdulajet** [comment]
Hello here is some emoji 👍🏾

**Comment by PandelisZ** [comment]
Greetings everyone! _weeeee_

**Comment by joenash** [comment]
💖  ✨  🎉

**Comment by alyssais** [comment]
Hi @swinton!

**Comment by swinton** [comment]
**Hello World** 🌎

**Comment by juanpflores** [comment]
Hey @swinton! 👍

**Comment by sourabhlal** [comment]
_This is a comment_

**Comment by joenash** [comment]
Here's a team! @campus-experts/fall-2016

**Comment by swinton** [comment]
:wave: thanks everyone, I'll close this issue, but please feel free to reach out with any questions via additional comments here :smile:

**Comment by joenash** [comment]
Thanks so much!
