### ISSUE TITLE
Phil Nash, Browsers behind your back, Tuesday 2nd May

### ISSUE THREAD

**Issue by joenash** [campus-experts/spring-2017#48]
This Tuesday, Phil Nash from Twilio will be speaking about:

Browsers behind your back
You've probably heard of the magic of a Service Worker when a user is offline, but what can we do for them when they get back online? We can take advantage of the Service Worker's life outside of the page and start to perform actions in the background. In this talk we'll investigate the Background Sync API and the APIs that it depends upon, we'll look at what you might use it for and see it in action. Once that is behind us we can take a peek into the future and even more background tasks with a look at the Periodic Sync API.

The talk will be at 5:30pm UK, 9:30am SF, full timezones here: https://www.timeanddate.com/worldclock/converter.html?iso=20170504T163000&p1=136&p2=224&p3=75&p4=267&p5=37&p6=2408&p7=241

Link: https://github.zoom.us/j/4245140792

**Comment by BlueHatbRit** [comment]
The post with the new time updated the converter link.

**Comment by joenash** [comment]
Slides and links here! https://t.co/TbBVVqOybW

**Comment by joenash** [comment]
https://www.dropbox.com/s/a54bjekn69n848a/philnashserviceworkers.mp4?dl=0
